openapi: "3.0.3"
servers:
  - url: https://api.conekta.io
    description: conekta main server
info:
  description: Conekta sdk 
  version: 1.0.0
  contact:
    name: api support client
    url:  https://github.com/conekta/openapi/issues
    email: engineering@conekta.com
  title: Conekta API
  license:
    name: MIT-LICENSE
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /antifraud/whitelists:
    $ref: "./resources/antifraud/whitelists/get_create_delete.yml"
  /antifraud/blacklists:
    $ref: "./resources/antifraud/blacklists/get_create_delete.yml"
  /customers:
    $ref: "./resources/customers/create_customer.yml"
  /customers/{id}:
    $ref: "./resources/customers/get_customer.yml"
  /customers/{id}/fiscal_entities:
    $ref: "./resources/customers/create_customer_fiscal_entities.yml"
  /customers/{id}/fiscal_entities/{fiscal_entities_id}:
    $ref: "./resources/customers/update_customer_fiscal_entities.yml"
  /customers/{id}/payment_sources:
    $ref: "./resources/customers/create_customer_payment_sources.yml"
  /customers/{id}/payment_sources/{payment_sources_id}:
    $ref: "./resources/customers/update_customer_payment_sources.yml"
  /customers/{id}/shipping_contacts:
    $ref: "./resources/customers/create_customer_shipping_contacts.yml"
  /customers/{id}/shipping_contacts/{shipping_contacts_id}:
    $ref: "./resources/customers/update_customer_shipping_contacts.yml"
  /events:
    $ref: "./resources/events/events.yml"
  /events/{id}:
    $ref: "./resources/events/event.yml"
  /logs:
     $ref: "./resources/logs/log.yml"
  /logs/{id}:
    $ref: "./resources/logs/log_by_id.yml"
  /orders:
    $ref: "./resources/orders/order.yml"
  /orders/{id}:
    $ref: "./resources/orders/order_param.yml"
  /orders/{id}/capture:
    $ref: "./resources/orders/order_capture_param.yml"
  /orders/{id}/charges:
    $ref: "./resources/orders/order_charge_param.yml"
  /orders/{id}/discount_lines:
    $ref: "./resources/orders/discount_lines_param.yml"
  /orders/{id}/discount_lines/{discount_lines_id}:
    $ref: "./resources/orders/update_order_discount_lines_param.yml"
  /orders/{id}/line_items:
    $ref: "./resources/orders/order_line_items_param.yml"
  /orders/{id}/line_items/{line_item_id}:
    $ref: "./resources/orders/update_order_line_items_param.yml"
  /orders/{id}/refunds:
    $ref: "./resources/orders/order_refunds_param.yml"
  /orders/{id}/shipping_lines:
    $ref: "./resources/orders/order_shipping_lines_param.yml"
  /orders/{id}/shipping_lines/{shipping_lines_id}:
    $ref: "./resources/orders/update_order_shipping_lines_param.yml"
  /orders/{id}/tax_lines:
    $ref: "./resources/orders/order_tax_lines_param.yml"
  /orders/{id}/tax_lines/{tax_lines_id}:
    $ref: "./resources/orders/update_order_tax_lines_param.yml"
  /plans:
    $ref: "./resources/plans/plans.yml"
  /plans/{id}:
    $ref: "./resources/plans/plan.yml"
  /webhooks:
     $ref: "./resources/webhooks/webhooks.yml"
  /webhooks/{id}:
     $ref: "./resources/webhooks/webhook.yml"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    