openapi: "3.0.3"
servers:
  - url: https://api.conekta.io
    description: conekta main server
info:
  description: Conekta sdk 
  version: 1.0.0
  contact:
    name: api support client
    url:  https://github.com/conekta/openapi/issues
    email: engineering@conekta.com
  title: Conekta API
  license:
    name: MIT-LICENSE
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /antifraud/whitelists:
    $ref: "./resources/antifraud/whitelists/get_create_delete.yml"
  /antifraud/blacklists:
    $ref: "./resources/antifraud/blacklists/get_create_delete.yml"
  /customers:
    $ref: "./resources/customers/create_customer.yml"
  /customers/{id}:
    $ref: "./resources/customers/get_customer.yml"
  /logs:
     $ref: "./resources/logs/log.yml"
  /logs/{id}:
    $ref: "./resources/logs/log_by_id.yml"
  /orders:
    $ref: "./resources/orders/order.yml"
  /orders/{id}:
    $ref: "./resources/orders/order_param.yml"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    