openapi: "3.0.3"
servers:
  - url: https://api.conekta.io
    description: conekta main server
info:
  description: Conekta sdk 
  version: 1.0.0
  contact:
    name: api support client
    url:  https://github.com/conekta/openapi/issues
    email: engineering@conekta.com
  title: Conekta API
  license:
    name: MIT-LICENSE
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /customers:
    $ref: "./resources/customers/create_customer.yml"
  /customers/{id}:
    $ref: "./resources/customers/get_customer.yml"
  /logs:
     $ref: "./resources/logs/log.yml"
  /logs/{id}:
    $ref: "./resources/logs/log_by_id.yml"
  /orders:
    $ref: "./resources/orders/order.yml"
  /orders/{id}:
    $ref: "./resources/orders/order_param.yml"
  /orders/{id}/charges:
    $ref: "./resources/orders/order_charge_param.yml"
  /orders/{id}/discount_lines:
    $ref: "./resources/orders/discount_lines_param.yml"
  /orders/{id}/discount_lines/{discount_lines_id}:
    $ref: "./resources/orders/update_order_discount_lines_param.yml"
  /orders/{id}/line_items:
    $ref: "./resources/orders/order_line_items_param.yml"
  /orders/{id}/shipping_lines:
    $ref: "./resources/orders/order_shipping_lines_param.yml"
  /orders/{id}/shipping_lines/{shipping_lines_id}:
    $ref: "./resources/orders/update_order_shipping_lines_param.yml"
  /orders/{id}/tax_lines:
    $ref: "./resources/orders/order_tax_lines_param.yml"
  /orders/{id}/tax_lines/{tax_lines_id}:
    $ref: "./resources/orders/update_order_tax_lines_param.yml"
  /orders/{id}/line_items/{line_item_id}:
    $ref: "./resources/orders/update_order_line_items_param.yml"
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    